# Generated by Django 4.1 on 2022-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refugio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image_1', models.ImageField(blank=True, upload_to='refugio_image/')),
                ('image_2', models.ImageField(blank=True, upload_to='refugio_image/')),
                ('image_3', models.ImageField(blank=True, upload_to='refugio_image/')),
                ('image_4', models.ImageField(blank=True, upload_to='refugio_image/')),
            ],
        ),
    ]
