# Generated by Django 4.1 on 2022-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refugio', '0002_perfil_refugio'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='logo',
            field=models.ImageField(blank=True, upload_to='refugio_image/'),
        ),
    ]
