# Generated by Django 4.1 on 2022-08-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Refugio', '0003_refugio_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_refugio',
            name='refugio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RefugioProf', to='Refugio.refugio'),
        ),
    ]
