# Generated by Django 4.1 on 2022-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refugio', '0004_perfil_refugio_refugio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_refugio',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
