# Generated by Django 4.1 on 2022-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refugio', '0006_alter_perfil_refugio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='refugio_image/'),
        ),
    ]
