# Generated by Django 4.1 on 2022-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
