# Generated by Django 4.1 on 2022-08-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0003_alter_mascota_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_aprox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mascota_image/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
